-- Dedicated server role; provision its password separately in the service dashboard.
CREATE ROLE mabhazi_api NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT;
GRANT USAGE ON SCHEMA public TO mabhazi_api;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public."auth_deletion_jobs" TO mabhazi_api;
CREATE POLICY api_server_access ON public."auth_deletion_jobs" FOR ALL TO mabhazi_api USING (true) WITH CHECK (true);
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public."sessions" TO mabhazi_api;
CREATE POLICY api_server_access ON public."sessions" FOR ALL TO mabhazi_api USING (true) WITH CHECK (true);
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public."users" TO mabhazi_api;
CREATE POLICY api_server_access ON public."users" FOR ALL TO mabhazi_api USING (true) WITH CHECK (true);
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public."journey_stops" TO mabhazi_api;
CREATE POLICY api_server_access ON public."journey_stops" FOR ALL TO mabhazi_api USING (true) WITH CHECK (true);
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public."journeys" TO mabhazi_api;
CREATE POLICY api_server_access ON public."journeys" FOR ALL TO mabhazi_api USING (true) WITH CHECK (true);
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public."proposed_associations" TO mabhazi_api;
CREATE POLICY api_server_access ON public."proposed_associations" FOR ALL TO mabhazi_api USING (true) WITH CHECK (true);
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public."journey_ratings" TO mabhazi_api;
CREATE POLICY api_server_access ON public."journey_ratings" FOR ALL TO mabhazi_api USING (true) WITH CHECK (true);
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public."search_events" TO mabhazi_api;
CREATE POLICY api_server_access ON public."search_events" FOR ALL TO mabhazi_api USING (true) WITH CHECK (true);
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public."journey_reports" TO mabhazi_api;
CREATE POLICY api_server_access ON public."journey_reports" FOR ALL TO mabhazi_api USING (true) WITH CHECK (true);
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public."journey_claims" TO mabhazi_api;
CREATE POLICY api_server_access ON public."journey_claims" FOR ALL TO mabhazi_api USING (true) WITH CHECK (true);
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public."journey_contributions" TO mabhazi_api;
CREATE POLICY api_server_access ON public."journey_contributions" FOR ALL TO mabhazi_api USING (true) WITH CHECK (true);
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public."cities" TO mabhazi_api;
CREATE POLICY api_server_access ON public."cities" FOR ALL TO mabhazi_api USING (true) WITH CHECK (true);
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public."bus_companies" TO mabhazi_api;
CREATE POLICY api_server_access ON public."bus_companies" FOR ALL TO mabhazi_api USING (true) WITH CHECK (true);
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public."abuse_reports" TO mabhazi_api;
CREATE POLICY api_server_access ON public."abuse_reports" FOR ALL TO mabhazi_api USING (true) WITH CHECK (true);
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO mabhazi_api;
